import './style.css';
import { createScene } from './scene.js';
import { seedLayout,validateLayout,areaOf,validPolygon,polygonInside,rupees,number,STORAGE_KEY,toGeoJSON } from './model.js';
import { createGoogleView } from './maps.js';
const $=selector=>document.querySelector(selector);
let layout=seedLayout(),loadWarning='';
try{const saved=localStorage.getItem(STORAGE_KEY);if(saved)layout=validateLayout(JSON.parse(saved));}catch{loadWarning='Saved layout could not be loaded. Showing the sample; export it before making changes if you need a backup.';}
let selected=layout.plots[0].id,statusFilter='all',editing=false,scene,drawKind=null,drawPoints=[],toastTimer,apiKey=import.meta.env.VITE_GOOGLE_MAPS_API_KEY||'';
const portfolioUrl=import.meta.env.VITE_PORTFOLIO_URL||(import.meta.env.DEV?'http://127.0.0.1:5173':'/');$('#portfolio-link').href=portfolioUrl;$('#contact-link').href=`${portfolioUrl.replace(/\/$/,'')}/#contact`;
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,6500);}
function persist(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(layout));$('#save-state').textContent='● Saved on this device';}catch{$('#save-state').textContent='○ Unsaved — export a backup';toast('Browser storage is unavailable or full. Export your layout to keep these changes.');}}
const current=()=>layout.plots.find(plot=>plot.id===selected)||layout.plots[0];
function selectPlot(id){selected=id;render();}
function renderList(){
  const focusedId=document.activeElement?.dataset?.plotId;
  const query=$('#search').value.trim().toLowerCase();const plots=layout.plots.filter(p=>(statusFilter==='all'||p.status===statusFilter)&&p.name.toLowerCase().includes(query));
  $('#visible-count').textContent=`${plots.length} plots`;
  $('#plot-list').replaceChildren(...plots.map(p=>{
    const b=document.createElement('button');b.dataset.plotId=p.id;b.className=p.id===selected?'selected':'';b.setAttribute('aria-pressed',String(p.id===selected));b.setAttribute('aria-label',`Plot ${p.name}, ${p.status}, ${number(p.area)} square metres, ${rupees(p.area*p.rate)}`);
    const left=document.createElement('div'),right=document.createElement('div');const name=document.createElement('div');name.className='list-name';name.textContent=`Plot ${p.name}`;const area=document.createElement('div');area.className='list-area';area.textContent=`${number(p.area)} m²`;left.append(name,area);const price=document.createElement('div');price.className='list-price';price.textContent=rupees(p.area*p.rate);const status=document.createElement('div');status.className='list-status';const dot=document.createElement('i');dot.className=p.status;status.append(dot,document.createTextNode(p.status[0].toUpperCase()+p.status.slice(1)));right.append(price,status);b.append(left,right);b.addEventListener('click',()=>selectPlot(p.id));return b;
  }));
  if(!plots.length){const p=document.createElement('p');p.className='empty-state';p.textContent='No plots match. Try another name or availability filter.';$('#plot-list').append(p);}
  if(focusedId){[...$('#plot-list').children].find(el=>el.dataset.plotId===focusedId)?.focus({preventScroll:true});}
}
function render(){const p=current();selected=p.id;renderList();$('#total-plots').textContent=layout.plots.length;$('#available-plots').textContent=layout.plots.filter(p=>p.status==='available').length;$('#site-area').textContent=number(areaOf(layout.boundary));$('#detail-name').textContent=`Plot ${p.name}`;$('#detail-status').textContent=p.status[0].toUpperCase()+p.status.slice(1);$('#detail-status').className=`status-tag ${p.status}`;$('#preview-shape').textContent=p.name;
  const xs=p.points.map(p=>p[0]),zs=p.points.map(p=>p[1]);$('#preview-width').textContent=`${number(Math.max(...xs)-Math.min(...xs))} m span`;$('#preview-depth').textContent=`${number(Math.max(...zs)-Math.min(...zs))} m span`;$('#detail-area').textContent=`${number(p.area)} m²`;$('#detail-rate').textContent=rupees(p.rate);$('#detail-total').textContent=rupees(p.area*p.rate);const interested=layout.interests.includes(p.id);$('#detail-interest').textContent=`${number(p.interested+(interested?1:0))} people interested`;$('#interest').textContent=p.status==='sold'?'Plot sold':interested?'♥ Interest saved · undo':'♡ I’m interested';$('#interest').disabled=p.status==='sold';$('#interest').setAttribute('aria-pressed',String(interested));$('#detail-note').textContent=p.note||'No additional notes for this plot.';$('#edit-plot').hidden=!editing;scene?.rebuild(layout,selected);
}
try{scene=createScene($('#scene'),{onSelect:selectPlot,onPoint:addPoint,onHover:(id,position)=>{const tip=$('#tooltip');if(!id||drawKind){tip.hidden=true;return;}const p=layout.plots.find(p=>p.id===id);tip.replaceChildren();const title=document.createElement('strong');title.textContent=`Plot ${p.name}`;tip.append(title);[`${number(p.area)} m² · ${rupees(p.rate)} / m²`,`${rupees(p.area*p.rate)} estimated price`,`${p.interested+(layout.interests.includes(p.id)?1:0)} people interested`].forEach(text=>{const line=document.createElement('p');line.textContent=text;tip.append(line);});tip.hidden=false;const bounds=$('#scene-wrap');tip.style.left=`${Math.max(8,Math.min(position.x+16,bounds.clientWidth-tip.offsetWidth-8))}px`;tip.style.top=`${Math.max(8,Math.min(position.y-25,bounds.clientHeight-tip.offsetHeight-8))}px`;}});}catch(error){$('#scene-fallback').hidden=false;$('#scene-instructions').hidden=true;console.warn('3D scene unavailable:',error.message);}
function setMode(active){editing=active;$('#explore-mode').classList.toggle('active',!active);$('#edit-mode').classList.toggle('active',active);$('#explore-mode').setAttribute('aria-pressed',String(!active));$('#edit-mode').setAttribute('aria-pressed',String(active));$('#editor-toolbar').hidden=!active;$('#edit-plot').hidden=!active;if(!active)cancelDrawing();toast(active?'Editing enabled. Changes are saved only on this device.':'Explore mode. Choose a plot to see its details.');}
$('#explore-mode').onclick=()=>setMode(false);$('#edit-mode').onclick=()=>setMode(true);
$('#search').addEventListener('input',renderList);
document.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>{statusFilter=b.dataset.status;document.querySelectorAll('[data-status]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});renderList();});
$('#interest').onclick=()=>{const p=current();if(p.status==='sold')return;layout.interests=layout.interests.includes(p.id)?layout.interests.filter(id=>id!==p.id):[...layout.interests,p.id];persist();render();toast(layout.interests.includes(p.id)?`Your interest in ${p.name} is saved on this device. No enquiry was sent.`:'Your saved interest has been removed.');};
function setView(mode){scene?.setView(mode);$('#view-3d').classList.toggle('active',mode==='3d');$('#view-2d').classList.toggle('active',mode==='2d');$('#view-3d').setAttribute('aria-pressed',String(mode==='3d'));$('#view-2d').setAttribute('aria-pressed',String(mode==='2d'));$('#rotate').disabled=mode==='2d';}
$('#view-3d').onclick=()=>{cancelDrawing();setView('3d');};$('#view-2d').onclick=()=>{cancelDrawing();setView('2d');};$('#zoom-in').onclick=()=>scene?.zoom(1.2);$('#zoom-out').onclick=()=>scene?.zoom(1/1.2);$('#rotate').onclick=()=>scene?.rotate();$('#reset-view').onclick=()=>scene?.reset();
document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#edit-plot').onclick=()=>{const p=current();$('#edit-name').value=p.name;$('#edit-area').value=p.area;$('#edit-rate').value=p.rate;$('#edit-status').value=p.status;$('#edit-interest').value=p.interested;$('#edit-note').value=p.note;$('#edit-error').textContent='';$('#edit-dialog').showModal();};
$('#edit-form').onsubmit=event=>{event.preventDefault();const p=current();const updated={...p,name:$('#edit-name').value.trim(),area:Number($('#edit-area').value),rate:Number($('#edit-rate').value),status:$('#edit-status').value,interested:Number($('#edit-interest').value),note:$('#edit-note').value.trim()};try{layout=validateLayout({...layout,plots:layout.plots.map(x=>x.id===p.id?updated:x)});}catch(error){$('#edit-error').textContent=error.message;return;}persist();render();$('#edit-dialog').close();toast(`Plot ${updated.name} updated.`);};
function openSettings(){ $('#latitude').value=layout.origin.lat;$('#longitude').value=layout.origin.lng;$('#api-key').value=apiKey;$('#settings-dialog').showModal(); }
$('#settings').onclick=openSettings;
$('#settings-form').onsubmit=event=>{event.preventDefault();layout.origin={lat:Number($('#latitude').value),lng:Number($('#longitude').value)};const nextKey=$('#api-key').value.trim();if(apiKey!==nextKey&&window.google?.maps)toast('API key changed. Reload this page to reconnect with a different key.');else toast('Site settings saved. Coordinates apply to all plot boundaries.');apiKey=nextKey;persist();$('#settings-dialog').close();};
function download(data,filename){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#export').onclick=()=>{download(layout,'happy-city-layout.json');toast('Layout exported. Keep this file as a backup.');};$('#geojson').onclick=()=>{download(toGeoJSON(layout),'happy-city-boundaries.geojson');toast('Geographic boundaries exported as GeoJSON.');};
$('#import').onclick=()=>$('#import-file').click();$('#import-file').onchange=async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>2e6)throw Error('Please choose a layout file smaller than 2 MB.');const next=validateLayout(JSON.parse(await file.text()));layout=next;selected=next.plots[0].id;cancelDrawing();persist();render();toast('Layout imported successfully.');}catch(error){toast(`Import rejected: ${error.message}`);}event.target.value='';};
$('#reset-data').onclick=()=>{$('#settings-dialog').close();$('#confirm-dialog').showModal();};$('#confirm-reset').onclick=()=>{layout=seedLayout();selected=layout.plots[0].id;cancelDrawing();persist();render();$('#confirm-dialog').close();toast('The original sample layout has been restored.');};
function startDrawing(kind){if(!scene){toast('Drawing requires WebGL. Try Google Maps or a browser with hardware acceleration.');return;}cancelDrawing();drawKind=kind;drawPoints=[];setView('2d');scene.setDrawing(true);$('#draw-bar').hidden=false;$('#scene-instructions').hidden=true;$('#tooltip').hidden=true;$('#draw-instruction').textContent=`Click at least 3 corners for the ${kind==='boundary'?'site boundary':'new plot'}.`;
}
function addPoint(point){if(!drawKind)return;if(drawPoints.length>=200){toast('Maximum 200 corners per shape.');return;}drawPoints.push(point);scene?.draw(drawPoints);$('#draw-instruction').textContent=`${drawPoints.length} corners marked · ${number(areaOf(drawPoints))} m² · Finish to close the shape`;
}
function cancelDrawing(){drawKind=null;drawPoints=[];scene?.setDrawing(false);scene?.draw([]);$('#draw-bar').hidden=true;$('#scene-instructions').hidden=!scene;}
function commitShape(kind,points){if(!validPolygon(points))throw Error('Choose at least 3 distinct corners with 1 m² or more. Edges must not cross.');if(kind==='boundary'){if(!layout.plots.every(p=>polygonInside(p.points,points)))throw Error('The site boundary must contain all existing plots. Draw a larger boundary.');layout.boundary=points;}else{if(layout.plots.length>=500)throw Error('This layout supports up to 500 plots.');if(!polygonInside(points,layout.boundary))throw Error('Draw the new plot entirely inside the site boundary.');let i=1;while(layout.plots.some(p=>p.name.toLowerCase()===`new ${i}`))i++;const plot={id:crypto.randomUUID(),name:`New ${i}`,points,area:Math.round(areaOf(points)*100)/100,rate:8500,interested:0,status:'available',note:'Newly drawn plot. Confirm the dimensions with a survey.'};layout.plots.push(plot);selected=plot.id;}persist();render();toast(kind==='boundary'?'Site boundary saved.':'New plot created. Use the pencil to rename it and set pricing.');}
$('#draw-boundary').onclick=()=>startDrawing('boundary');$('#draw-plot').onclick=()=>startDrawing('plot');$('#cancel-draw').onclick=cancelDrawing;$('#undo-point').onclick=()=>{drawPoints.pop();scene?.draw(drawPoints);$('#draw-instruction').textContent=`${drawPoints.length} corners marked. Click to add more.`;};$('#finish-draw').onclick=()=>{try{commitShape(drawKind,drawPoints.map(p=>[...p]));cancelDrawing();}catch(error){toast(error.message);}};
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&drawKind)cancelDrawing();});
const googleView=createGoogleView({getLayout:()=>layout,getApiKey:()=>apiKey,isEditing:()=>editing,onOrigin:origin=>{layout.origin=origin;persist();toast('Site centre moved. Plot offsets are preserved.');},onShape:commitShape,onSelect:selectPlot,onSettings:()=>{$('#google-dialog').close();openSettings();}});
$('#google-open').onclick=()=>{cancelDrawing();googleView.open();};
render();if(loadWarning)toast(loadWarning);
