import { localToGeo,geoToLocal } from './model.js';
export function createGoogleView({getLayout,getApiKey,isEditing,onOrigin,onShape,onSelect,onSettings}){
  const $=s=>document.querySelector(s);let loadedKey='',map=null,panorama=null,overlays=[],kind=null,points=[],preview=null,currentView='satellite',requestId=0,loading=null;
  const status=text=>$('#google-status').textContent=text;
  async function load(){if(window.google?.maps?.importLibrary)return;if(loading)return loading;const key=getApiKey();if(!key)throw Error('Add your Google Maps API key in Site settings to connect.');loadedKey=key;
    loading=new Promise((resolve,reject)=>{const script=document.createElement('script');const callback=`happyCityMapsReady${Date.now()}`;const timer=setTimeout(()=>{reject(Error('Google Maps took too long to load. Check your connection and API key.'));loading=null;},20000);window[callback]=()=>{clearTimeout(timer);delete window[callback];resolve();};window.gm_authFailure=()=>{status('Google Maps could not authenticate. Check API enablement, billing, and key restrictions.');};script.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(key)}&loading=async&callback=${callback}&v=weekly`;script.async=true;script.onerror=()=>{clearTimeout(timer);delete window[callback];loading=null;reject(Error('Google Maps could not load. Check your internet connection.'));};document.head.append(script);});return loading;
  }
  function clear(){overlays.forEach(p=>p.setMap(null));overlays=[];preview?.setMap(null);preview=null;kind=null;points=[];if(panorama){panorama.setVisible(false);panorama=null;}map=null;$('#google-container').replaceChildren();}
  function renderPolygons(){if(!map)return;overlays.forEach(p=>p.setMap(null));overlays=[];const layout=getLayout();const boundary=new google.maps.Polygon({paths:layout.boundary.map(p=>localToGeo(p,layout.origin)),map,strokeColor:'#8f7140',strokeWeight:2,fillOpacity:.05,clickable:false});overlays.push(boundary);layout.plots.forEach(p=>{const polygon=new google.maps.Polygon({paths:p.points.map(pt=>localToGeo(pt,layout.origin)),map,strokeColor:'#fffaf0',strokeWeight:2,fillColor:{available:'#99b16c',reserved:'#d5b865',sold:'#a7afa0'}[p.status],fillOpacity:.6,clickable:!kind});polygon.addListener('click',()=>{onSelect(p.id);status(`Selected plot ${p.name}. Close this map to see its details.`);});overlays.push(polygon);});}
  async function show(view){currentView=view;const id=++requestId;document.querySelectorAll('[data-google-view]').forEach(b=>b.classList.toggle('active',b.dataset.googleView===view));clear();$('#google-settings').hidden=false;$('#google-edit-tools').hidden=true;status('Connecting to Google Maps…');try{await load();if(id!==requestId||!$('#google-dialog').open)return;$('#google-settings').hidden=true;const origin=getLayout().origin;
      if(view==='satellite'){const {Map}=await google.maps.importLibrary('maps');if(id!==requestId||!$('#google-dialog').open)return;map=new Map($('#google-container'),{center:origin,zoom:19,mapTypeId:'satellite',streetViewControl:true,mapTypeControl:true,gestureHandling:'greedy'});renderPolygons();$('#google-edit-tools').hidden=!isEditing();status('Sample coordinates until you set your real site location. Click the map to move the site centre.');map.addListener('click',event=>{const point=event.latLng.toJSON();if(kind){points.push(geoToLocal(point,getLayout().origin));preview?.setMap(null);preview=new google.maps.Polyline({path:points.map(p=>localToGeo(p,getLayout().origin)),map,strokeColor:'#ef873c',strokeWeight:3});status(`${points.length} corners marked. Finish shape to save.`);}else{onOrigin(point);renderPolygons();}});
      }else if(view==='street'){const {StreetViewService,StreetViewPanorama}=await google.maps.importLibrary('streetView');const {data}=await new StreetViewService().getPanorama({location:origin,radius:100,preference:'NEAREST'});if(id!==requestId||!$('#google-dialog').open)return;panorama=new StreetViewPanorama($('#google-container'),{pano:data.location.pano,pov:{heading:0,pitch:0},visible:true});status(`Nearest available panorama within 100 m. Imagery date: ${data.imageDate||'not supplied'}. This may be on a nearby road rather than inside the plot.`);
      }else{const {Map3DElement}=await google.maps.importLibrary('maps3d');if(id!==requestId||!$('#google-dialog').open)return;const view3d=new Map3DElement({center:{...origin,altitude:0},range:900,tilt:60,heading:20,mode:'HYBRID'});$('#google-container').append(view3d);status('Google 3D surroundings. Detailed buildings and trees depend on coverage; custom plot overlays are shown in Satellite & boundaries.');}
    }catch(error){if(id!==requestId||!$('#google-dialog').open)return;status(view==='street'&&window.google?.maps?'No Street View panorama could be loaded within 100 m. Try another location or check your API configuration.':error.message);$('#google-settings').hidden=false;}}
  document.querySelectorAll('[data-google-view]').forEach(b=>b.onclick=()=>show(b.dataset.googleView));$('#google-settings').onclick=onSettings;
  function start(value){if(!map)return;kind=value;points=[];preview?.setMap(null);preview=null;renderPolygons();status(`Click at least 3 corners on the satellite map to draw the ${value==='boundary'?'site boundary':'plot'}.`);}
  $('#google-boundary').onclick=()=>start('boundary');$('#google-plot').onclick=()=>start('plot');$('#google-cancel').onclick=()=>{kind=null;points=[];preview?.setMap(null);preview=null;renderPolygons();status('Drawing cancelled.');};$('#google-finish').onclick=()=>{if(!kind){status('Choose Draw site boundary or Draw plot first.');return;}try{onShape(kind,points.map(p=>[...p]));kind=null;points=[];preview?.setMap(null);preview=null;renderPolygons();status('Shape saved to the layout.');}catch(error){status(error.message);}};
  $('#google-dialog').addEventListener('close',()=>{requestId++;clear();});
  return {open(){ $('#google-dialog').showModal();show(currentView); }};
}
